### ISSUE TITLE
Journal page breaks if the scene doesn't exist

### ISSUE THREAD

**Issue by aquavitae** [claypooj21/journals-like-a-script#3]
If the scene ID is wrong or doesn't exist, the entire journal breaks, here: https://github.com/claypooj21/journals-like-a-script/blob/4dfcfaeb8f4f68e71ac102b79b61039795212dc3/modules/jlas.js#L62-L66

The problem is that if `doc` couldn't be resolved, `broken` is set to true, but then `if ( !doc.canUserModify(game.user, "update" )...` bombs out because `doc` is still undefined. I think this needs to be something like `if (doc && !doc.canUserModify(...`.

**Comment by claypooj21** [comment]
Hey @aquavitae! Thanks for the feedback!

You were right; that was absolutely the line breaking the whole thing. I missed that during testing, so thanks for reporting it. I rewrote jlas.js to consolidate all the sporadic `if broken ? ... : ...` statements into one over-arching `if else`:
```javascript
     if (!doc) {
        // Update link data, and flag it as broken
        data.name = data.name || target;
        data.icon = "fas fa-unlink";
        data.dataset = { type, entity: doc_type, id: null };
        data.cls.push("broken");
    } else {
        // Check if the user has permissions to use this link. If not, determine
        // how much of the link should show based on the settings.
        if (!doc.canUserModify(game.user, "update") && activate) {
            const visibility = game.settings.get("journals-like-a-script", "sceneLinkVisibility");
            if (visibility == 1) return document.createTextNode(`${data.name}`);
            if (visibility == 2) return document.createElement('wbr');
        };

        // Update link data
        data.name = data.name || doc.name;
        data.icon = config.sidebarIcon;
        data.dataset = { type, entity: doc_type, id: doc.id };
    };
```

I'm going to close this issue. Please let me know if you find anything else, and thanks again!
